
# NOTE: each operator is one quadruplet
EQUAL_QUAD = '='

CLS_QUAD = 'CLS'
OUTPUT_QUAD = 'OUTPUT'
INPUT_QUAD = 'INPUT'

GOTOF_QUAD = 'GOTOF'
GOTO_QUAD = 'GOTO'

CALL_SUB_PROCEDURE_QUAD = 'CALL_SUB_PROCEDURE'
END_SUB_PROCEDURE_QUAD = 'END_SUB_PROCEDURE'

END_PROGRAM_QUAD = 'END_PROGRAM'